<?php 
include 'config.php';
include 'seo.php';
?>
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="title" content="<?php echo $title;?>">
    <meta name="keywords" content="<?php echo $keywords;?>">
    <meta name="description" content="<?php echo $description;?>">
    <meta name="Robots" content="INDEX,FOLLOW">
    <meta name="theme-color" content="#216ff3">
    <link rel="manifest" href="<?php echo baseUrl;?>/manifest.json">
    <title>SV Engineering</title>

    <!-- Bootstrap core CSS -->
    <link href="<?php echo resourceUrl;?>/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="<?php echo resourceUrl;?>/css/modern-business.css" rel="stylesheet">
<link rel="shortcut icon" type="image/png" href="<?php echo resourceUrl;?>/images/favicon.jpg"/>
<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "S.V Engineering",
  "image" : "https://svengineeringworks.in/images/sv-engg-logo.png",
  "telephone" : "9843317798",
  "email" : "vvbala1995@gmail.com",
  "address" : {
    "@type" : "PostalAddress",
    "streetAddress" : "22/1,Main road",
    "addressLocality" : "tirunelveli",
    "addressRegion" : "tamilnadu",
    "addressCountry" : "india",
    "postalCode" : "627112"
  },
  "openingHoursSpecification" : {
    "@type" : "OpeningHoursSpecification",
    "dayOfWeek" : {
      "@type" : "DayOfWeek",
      "name" : "365 days"
    }
  },
  "url" : "https://svengineeringworks.in"
}
</script>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script defer src="https://www.googletagmanager.com/gtag/js?id=UA-116209989-1"></script>
<script defer>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-116209989-1');
</script>

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="index.php">SV Engineering</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="index.php">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="about.php">About</a>
            </li>
            
            <li class="nav-item">
              <a class="nav-link" href="printing-machinaries.php">Product</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="contact.php">Contact</a>
            </li> 
          </ul>
        </div>
      </div>
    </nav>