<?php 
require 'functions.php';
include 'seo.php';
//var_dump($_SESSION['svengg']['user']);
?>
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta http-equiv="Content-Type" name="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="title" content="<?php echo $title;?>">
    <meta name="keywords" content="<?php echo $keywords;?>">
    <meta name="description" content="<?php echo $description;?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="Robots" content="INDEX,FOLLOW">
    <meta name="theme-color" content="#216ff3">
    <link rel="shortcut icon" type="image/ico" href="<?php echo resourceUrl;?>/images/favicon.ico"/>
    <link rel="canonical" href="https://svengineeringworks.in" />
    <link rel="alternate" href="https://www.svengineeringworks.in" media="only screen">
    <link rel="manifest" href="<?php echo $manifetUrl = isProd ? '' : baseUrl;?>/manifest.json">
    <title>Printing machine sales and service by S.V Engineering,Tamil nadu</title>

    <meta property="og:title" content="Printing machine sales and service by S.V Engineering,Tamil nadu" />
    <meta property="og:site_name" content="https://svengineeringworks.in"/><m eta property="og:url" content="https://svengineeringworks.in" />
    <meta property="og:image" content="<?php echo resourceUrl;?>/images/offest-printing-service-provider.png" />
    <meta property="og:image:url" content="<?php echo resourceUrl;?>/images/offest-printing-service-provider.png" />
    <meta property="og:image:width" content="495" />
    <meta property="og:image:height" content="500" />
    <meta property="og:description" content="Printing machine sales and service by S.V Engineering,Tamil nadu" />
    
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="<?php echo resourceUrl;?>/css/modern-business.css" rel="stylesheet">
<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "S.V Engineering",
  "image" : "https://svengineeringworks.in/images/sv-engg-logo.png",
  "telephone" : "9843317798",
  "email" : "vvbala1995@gmail.com",
  "address" : {
    "@type" : "PostalAddress",
    "streetAddress" : "22/1,Main road",
    "addressLocality" : "tirunelveli",
    "addressRegion" : "tamilnadu",
    "addressCountry" : "india",
    "postalCode" : "627112"
  },
  "openingHoursSpecification" : {
    "@type" : "OpeningHoursSpecification",
    "dayOfWeek" : {
      "@type" : "DayOfWeek",
      "name" : "365 days"
    }
  },
  "url" : "https://svengineeringworks.in"
}
</script>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script defer src="https://www.googletagmanager.com/gtag/js?id=UA-116209989-1"></script>
<script defer>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-116209989-1');
</script>

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="/">SV Engineering</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="<?php echo baseUrl;?>">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="about.php">About</a>
            </li>
            
            <li class="nav-item">
              <a class="nav-link" href="printing-machinaries.php">Product</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="contact.php">Contact</a>
            </li> 
            <li class="nav-item" data-toggle="modal" data-target="#js-common_model">
              <a class="nav-link" href="#" data-submit="register">Register</a>
            </li>
            <li class="nav-item" data-toggle="modal" data-target="#js-common_model">
              <a class="nav-link" href="#" data-submit="login">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#" data-submit="logout">Logout</a>
            </li>
            <li class="nav-item" id="js-option-btn" data-toggle="modal" data-target="#js-option_model">
              <a class="nav-link" href="#">Options</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

<!-- The Modal open -->
  <div class="modal fade" id="js-common_model">
    <div class="modal-dialog">
      <div class="modal-content">
      
        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="js-modal-title">Login form</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        
        <!-- Modal body -->
        <div class="modal-body">
          <form action="#" id="js-common_popup" method="post">
            <div class="form-group">
              <label for="email">Email/Mobile:</label>
              <input type="text" class="form-control mobile_validate email_validate" id="email" placeholder="Enter email/mobile" name="email" data-min="10" data-max="13" required>
            </div>
            <div class="form-group">
              <label for="pwd">Password:</label>
              <input type="password" class="form-control" id="pwd" placeholder="Enter password" name="pswd" required>
            </div>
            <!-- <div class="form-group form-check">
              <label class="form-check-label">
                <input class="form-check-input" type="checkbox" name="remember"> Remember me
              </label>
            </div> -->
            <button type="submit" class="btn btn-primary js-popup-submit" value="">Submit</button>
            <button type="reset" class="btn btn-danger">Reset</button>
          </form>
        </div>
        
        <!-- Modal footer -->
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
        </div>
        
      </div>
    </div>
  </div>
<!-- The Modal close -->

<!-- The Modal open -->
  <div class="modal fade" id="js-option_model">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
      
        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="js-modal-title">Options</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        
        <!-- Modal body -->
        <div class="modal-body">
          <ul>
            <button class="btn btn-primary" data-submit="add_post">Add post</button>
            <button class="btn btn-primary" data-submit="list_post">List post</button>
          </ul>
          <div class="row">
            <div class="col-md-12 js-main-div">
              <form id='js-add_post_form' method="post" enctype="multipart/form-data" data-purpose='add' novalidate>
                <h2 class='js-prod_form_h2'> Add product</h2>
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="prod_cat">Machine catagory:</label>
                      <input type="text" class="form-control" id="prod_cat" name="prod_cat" required>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="machine_type">Machine type:</label>
                      <select class="form-control" id="machine_type" name="machine_type" required>
                        <option value="1">New</option>
                        <option value="0">Second hand</option>
                      </select>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-12">
                      <div class="form-group">
                        <label for="product_name">Name:</label>
                        <input type="text" class="form-control" id="product_name" name="product_name" required>
                      </div>
                  </div>
                </div>
                <span class="js-main-attr-span">
                <div class="row js-attr-row">
                  <div class="col-md-5">
                    <div class="form-group">
                      <label for="attr_name">Attribute name:</label>
                      <input type="text" class="form-control" name="attr_name[]" required>
                    </div>
                  </div>
                  <div class="col-md-5">
                      <div class="form-group">
                        <label for="attr_value">Attribute value:</label>
                        <input type="text" class="form-control" name="attr_value[]" required>
                      </div>
                  </div>
                  <div class="col-md-2">
                    <div class="form-group"><p>&nbsp;</p>
                      <label class="btn btn-info btn-sm js-attr-modifier" data-value='+'><i class="fa fa-plus"></i></label>
                      <label class="btn btn-info btn-sm js-attr-modifier" data-value='-'><i class="fa fa-trash"></i></label>
                    </div>
                  </div>
                </div>
                </span>
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                        <label for="prod_images">Product images:</label>
                        <input type="file" class="form-control" id="prod_images" name="images" required>
                      </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-6">
                    <button class="btn btn-primary js-prod_form_submit" data-id>Add</button>
                  </div>
                </div>
              </form>
              <div class="row">
                <div class="col-md-12">
              <table class="table table-borderless" id="js-prod_list_table">
                <thead>
                  <tr><td colspan="3"><h2> Your product list</h2></td></tr>
                  <tr>
                    <th>Image</th>
                    <th>Product name</th>
                    <th class="mobile_hidden">Specification</th>
                    <th class="mobile_hidden">Decsription</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  <tr class="list_product_tr hidden">
                    <td style="width: 7em;"></td>
                    <td></td>
                    <td class="mobile_hidden "></td>
                    <td class="mobile_hidden "></td>
                    <td colspan="2" data-id="">
                      <button class="btn btn-info js-prod_edit_btn"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></button>
                      <button class="btn btn-danger js-prod_delete_btn"><i class="fa fa-trash" aria-hidden="true"></i></button>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
            </div>
            </div>
          </div>
        </div>
        
        <!-- Modal footer -->
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
        </div>
        
      </div>
    </div>
  </div>
<!-- The Modal close -->